### ISSUE TITLE
Theme is broken

### ISSUE THREAD

**Issue by literon36** [discord-extensions/modern-indicators#7] opened 2023-07-08 10:00 UTC
It no longer shows unread/connected/current channels correctly. (on BetterDiscord)
![image](https://github.com/discord-extensions/modern-indicators/assets/125917933/a0c9a012-35fa-4b67-9d25-0f656790aa89)

**Comment by cobrabr** [comment] 2023-07-14 01:07
Same is happening while using it with Vencord.

**Comment by LuckFire** [comment] 2023-07-14 01:28
This is most likely due to Discord updating the class names. I will work on fixing this when I have the chance to.

**Comment by cobrabr** [comment] 2023-07-14 01:56
You're right. I was taking a quick look, it seems like they've removed the `content-1gYQeQ` class, and the divs that used to have them now have no class assigned to them:
![image](https://github.com/discord-extensions/modern-indicators/assets/724969/9b7554bf-4629-4863-9da4-dc9b4208b393)

I fiddled a bit with it, tried adding the class back in (it still exists, but breaks the design; they seem to have moved the padding and/or margin styles to other places in the CSS, so adding the class back in causes the channel names to be extra-indented) and also tried replacing the class with `> div` and `:first-child` in the CSS (it kinda works, but looks wonky).

**Comment by LuckFire** [comment] 2023-07-14 02:01
I wonder if that's intentional or not.. is this on all clients (stable, ptb, canary) or is it just specific ones?

Edit: I confirmed this to be on stable and canary, likely the case on ptb too.

**Comment by LuckFire** [comment] 2023-09-18 17:46
As of [this commit](https://github.com/discord-extensions/modern-indicators/commit/fba1548266768cab2630b64ef908b9951b21e188) and [this pull request](https://github.com/discord-extensions/modern-indicators/pull/9), the issue should be fixed.

**Closed as completed by LuckFire** 2023-09-18 17:46 UTC
Labels: bug

**Comment by literon36** [comment] 2023-09-19 12:27
Thanks for fixing! Really like the look of this neat little theme!
